; MCP Servers for Revit Installer - Generated by build-installer.ps1

[Setup]
AppName=MCP Servers for Revit
AppVersion=1.1.2
AppPublisher=MCP Servers for Revit
AppPublisherURL=https://github.com/chris4d/mcp-servers-for-revit
DefaultDirName={autopf}\MCP Servers for Revit
DefaultGroupName=MCP Servers for Revit
OutputDir=C:\dev\mcp-servers-for-revit\installer\output
OutputBaseFilename=mcp-servers-for-revit-setup
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "staged\2024\*"; DestDir: "{app}\RevitPlugins\2024"; Flags: recursesubdirs ignoreversion
Source: "staged\2025\*"; DestDir: "{app}\RevitPlugins\2025"; Flags: recursesubdirs ignoreversion
Source: "staged\2026\*"; DestDir: "{app}\RevitPlugins\2026"; Flags: recursesubdirs ignoreversion
Source: "staged\Server\*"; DestDir: "{app}\Server"; Flags: recursesubdirs ignoreversion

[Icons]
Name: "{group}\Uninstall MCP Servers for Revit"; Filename: "{uninstallexe}"

[Code]
const
  RevitRegKey = 'SOFTWARE\\Autodesk\\Revit\\Autodesk Revit ';
  ServerKey = 'mcp-server-for-revit';
  CommandSetFolder = 'revit_mcp_plugin\\Commands';

var
  Page: TWizardPage;
  SetPage: TWizardPage;
  ClaudeCB, CursorCB, OpencodeCB, AnythingLLMCB: TNewCheckBox;

var SetCBs: array[0..2] of TNewCheckBox;

function GetAppDataDir: String;
begin
  Result := GetEnv('APPDATA');
end;

function GetUserProfilePath: String;
begin
  Result := GetEnv('USERPROFILE');
end;

function IsNodeInstalled: Boolean;
var RC: Integer;
begin
  Result := Exec('cmd', '/c node --version >nul 2>&1', '', SW_HIDE, ewWaitUntilTerminated, RC) and (RC = 0);
end;

function IsRevitInstalled(Y: String): Boolean;
begin
  Result := RegKeyExists(HKLM, RevitRegKey + Y) or RegKeyExists(HKCU, RevitRegKey + Y);
end;

procedure PruneCommandSets(Src: String);
var CmdDir: String; I: Integer;
begin
  CmdDir := Src + '\\revit_mcp_plugin\\Commands';
  if not DirExists(CmdDir) then Exit;
  for I := 0 to High(SetCBs) do begin
    if not SetCBs[I].Checked then begin
      DelTree(CmdDir + '\\' + SetCBs[I].Caption, True, True, True);
      Log('Removed unselected command set: ' + SetCBs[I].Caption);
    end;
  end;
end;

// Assemble Commands\commandRegistry.json from the registry-entries.json
// fragments of the command sets the user kept selected. Skipped when the
// user already has a registry (their opt-ins are preserved).
procedure WriteCommandRegistry(Year: String);
var D, P, F, S, Entry: String; I: Integer; First: Boolean; Ch: Char; SL: TStringList;
begin
  D := GetAppDataDir + '\\Autodesk\\Revit\\Addins\\' + Year + '\\revit_mcp_plugin\\Commands';
  if not DirExists(D) then Exit;
  P := D + '\\commandRegistry.json';
  if FileExists(P) then Exit;
  S := '{"commands": [';
  First := True;
  for I := 0 to High(SetCBs) do
  begin
    if not SetCBs[I].Checked then Continue;
    F := D + '\\' + SetCBs[I].Caption + '\\registry-entries.json';
    if not FileExists(F) then Continue;
    SL := TStringList.Create;
    try
      SL.LoadFromFile(F);
      Entry := SL.Text;
    finally SL.Free; end;
    if (Length(Entry) >= 2) and (Entry[1] = '[') then Delete(Entry, 1, 1);
    while Length(Entry) > 0 do
    begin
      Ch := Entry[Length(Entry)];
      if (Ch = ']') or (Ch = #13) or (Ch = #10) then
        Delete(Entry, Length(Entry), 1)
      else
        Break;
    end;
    if Entry = '' then Continue;
    if not First then S := S + ',';
    S := S + Entry;
    First := False;
  end;
  S := S + ']}';
  SaveStringToFile(P, S, False);
  Log('Seeded command registry for ' + Year + ' from surviving set fragments');
end;

procedure CopyToRevitAddins(Year: String);
var Src, Dst: String; BAT: TStringList; RC: Integer; HadReg: Boolean;
begin
  Src := ExpandConstant('{app}\\RevitPlugins\\' + Year);
  Dst := GetAppDataDir + '\\Autodesk\\Revit\\Addins\\' + Year;
  if not DirExists(Src) then begin Log('Missing: ' + Src); Exit; end;
  PruneCommandSets(Src);
  ForceDirectories(Dst);
  // Preserve an existing command registry (user opt-ins) across reinstalls:
  // back it up before xcopy, restore after. Fresh installs get a registry
  // assembled from the surviving sets' fragments (all commands disabled).
  HadReg := FileExists(Dst + '\\revit_mcp_plugin\\Commands\\commandRegistry.json');
  if HadReg then
    if not CopyFile(Dst + '\\revit_mcp_plugin\\Commands\\commandRegistry.json', ExpandConstant('{tmp}\\cmdreg_' + Year + '.json'), False) then HadReg := False;
  BAT := TStringList.Create;
  try
    BAT.Add('@echo off');
    BAT.Add('xcopy "' + Src + '\\*" "' + Dst + '\\" /E /I /Y /Q');
    BAT.SaveToFile(ExpandConstant('{tmp}\\copy_' + Year + '.bat'));
  finally BAT.Free; end;
  Exec('cmd', '/c "' + ExpandConstant('{tmp}\\copy_' + Year + '.bat') + '"', '', SW_HIDE, ewWaitUntilTerminated, RC);
  if HadReg then
    CopyFile(ExpandConstant('{tmp}\\cmdreg_' + Year + '.json'), Dst + '\\revit_mcp_plugin\\Commands\\commandRegistry.json', False);
  if not HadReg then WriteCommandRegistry(Year);
  Log('Copied plugin to ' + Dst);
end;

procedure RemoveFromRevitAddins(Year: String);
var D: String;
begin
  D := GetAppDataDir + '\\Autodesk\\Revit\\Addins\\' + Year;
  if FileExists(D + '\\mcp-servers-for-revit.addin') then DeleteFile(D + '\\mcp-servers-for-revit.addin');
  if DirExists(D + '\\revit_mcp_plugin') then DelTree(D + '\\revit_mcp_plugin', True, True, True);
end;

procedure CleanTrailingCommas(var C: String);
var I, J: Integer;
begin
  for I := 1 to Length(C) do begin
    if C[I] = ',' then begin
      J := I + 1;
      while (J <= Length(C)) and ((C[J] = ' ') or (C[J] = #9) or (C[J] = #13) or (C[J] = #10)) do Inc(J);
      if (J <= Length(C)) and ((C[J] = '}') or (C[J] = ']')) then C[I] := ' ';
    end;
  end;
end;

// Path of the bundled server for this install, JSON-escaped (backslashes doubled).
function ServerPathJson(): String;
begin
  Result := ExpandConstant('{app}\Server\build\index.js');
  StringChangeEx(Result, '\', '\\', True);
end;

procedure GetNodeEntry(var Entry: String);
var SP: String;
begin
  SP := ServerPathJson();
  Entry := '"mcp-server-for-revit": {' + #13#10
         + '            "command": "node",' + #13#10
         + '            "args": ["' + SP + '"]' + #13#10
         + '        }';
end;

procedure GetOpenCodeEntry(var Entry: String);
var SP: String;
begin
  SP := ServerPathJson();
  Entry := '"mcp-server-for-revit": {' + #13#10
         + '            "type": "local",' + #13#10
         + '            "command": ["node", "' + SP + '"],' + #13#10
         + '            "enabled": true' + #13#10
         + '        }';
end;

procedure ReplaceNpxServerEntry(var C: String; OpenCodeStyle: Boolean);
var I, S, E, Depth: Integer; Block, Fresh: String;
begin
  S := Pos(ServerKey, C);
  if S = 0 then Exit;
  E := 0; Depth := 0;
  for I := S to Length(C) do begin
    if C[I] = '{' then begin
      if Depth = 0 then S := I;
      Depth := Depth + 1;
    end else if C[I] = '}' then begin
      Depth := Depth - 1;
      if Depth = 0 then begin E := I; Break; end;
    end;
  end;
  if E = 0 then Exit;
  Block := Copy(C, S, E - S + 1);
  if Pos('npx', Block) = 0 then Exit;
  if OpenCodeStyle then GetOpenCodeEntry(Fresh) else GetNodeEntry(Fresh);
  Delete(C, S, E - S + 1);
  Insert(Fresh, C, S);
  Log('Replaced npx server entry with bundled server');
end;

procedure ConfigureClaudeDesktop;
var P, C: String; SL: TStringList;
begin
  P := GetAppDataDir + '\\Claude\\claude_desktop_config.json';
  if not FileExists(P) then begin
    ForceDirectories(ExtractFilePath(P));
    SL := TStringList.Create;
    try
      SL.Add('{');
      SL.Add('    "mcpServers": {');
      SL.Add('        "mcp-server-for-revit": {');
      SL.Add('            "command": "node",');
      SL.Add('            "args": ["' + ServerPathJson() + '"]');
      SL.Add('        }');
      SL.Add('    }');
      SL.Add('}');
      SL.SaveToFile(P);
    finally SL.Free; end;
    Log('Created Claude Desktop config');
  end else begin
    SL := TStringList.Create;
    try
      SL.LoadFromFile(P); C := SL.Text;
      if Pos(ServerKey, C) > 0 then begin
        ReplaceNpxServerEntry(C, False);
        SL.Text := C;
        SL.SaveToFile(P);
      Exit;
      end;
      StringChangeEx(C, '"mcpServers": {',
        '"mcpServers": {' + #13#10 + '        "mcp-server-for-revit": {' + #13#10 + '            "command": "node",' + #13#10 + '            "args": ["' + ServerPathJson() + '"]' + #13#10 + '        },', True);
      CleanTrailingCommas(C);
      SL.Text := C;
      SL.SaveToFile(P);
    finally SL.Free; end;
    Log('Updated Claude Desktop config');
  end;
end;

procedure RemoveFromClaudeDesktop;
var P, C: String; SL: TStringList; S, E: Integer;
begin
  P := GetAppDataDir + '\\Claude\\claude_desktop_config.json';
  if not FileExists(P) then Exit;
  SL := TStringList.Create;
  try
    SL.LoadFromFile(P); C := SL.Text;
    S := Pos('"mcp-server-for-revit"', C);
    if S = 0 then Exit;
    E := Pos('}', Copy(C, S, Length(C)));
    if E = 0 then Exit;
    E := S + E - 1;
    if (E + 1 <= Length(C)) and (C[E + 1] = ',') then Inc(E);
    Delete(C, S, E - S + 1);
    CleanTrailingCommas(C);
    SL.Text := C; SL.SaveToFile(P);
  finally SL.Free; end;
end;

procedure ConfigureCursor;
var P, C: String; SL: TStringList;
begin
  P := GetUserProfilePath + '\\.cursor\\mcp.json';
  if not FileExists(P) then begin
    ForceDirectories(ExtractFilePath(P));
    SL := TStringList.Create;
    try
      SL.Add('{');
      SL.Add('    "mcpServers": {');
      SL.Add('        "mcp-server-for-revit": {');
      SL.Add('            "command": "node"');
      SL.Add('            "args": ["' + ServerPathJson() + '"]');
      SL.Add('        }');
      SL.Add('    }');
      SL.Add('}');
      SL.SaveToFile(P);
    finally SL.Free; end;
    Log('Created Cursor config');
  end else begin
    SL := TStringList.Create;
    try
      SL.LoadFromFile(P); C := SL.Text;
      if Pos(ServerKey, C) > 0 then begin
        ReplaceNpxServerEntry(C, False);
        SL.Text := C;
        SL.SaveToFile(P);
      Exit;
      end;
      StringChangeEx(C, '"mcpServers": {',
        '"mcpServers": {' + #13#10 + '        "mcp-server-for-revit": {' + #13#10 + '            "command": "node",' + #13#10 + '            "args": ["' + ServerPathJson() + '"]' + #13#10 + '        },', True);
      CleanTrailingCommas(C);
      SL.Text := C;
      SL.SaveToFile(P);
    finally SL.Free; end;
    Log('Updated Cursor config');
  end;
end;

procedure RemoveFromCursor;
var P, C: String; SL: TStringList; S, E: Integer;
begin
  P := GetUserProfilePath + '\\.cursor\\mcp.json';
  if not FileExists(P) then Exit;
  SL := TStringList.Create;
  try
    SL.LoadFromFile(P); C := SL.Text;
    S := Pos('"mcp-server-for-revit"', C);
    if S = 0 then Exit;
    E := Pos('}', Copy(C, S, Length(C)));
    if E = 0 then Exit;
    E := S + E - 1;
    if (E + 1 <= Length(C)) and (C[E + 1] = ',') then Inc(E);
    Delete(C, S, E - S + 1);
    CleanTrailingCommas(C);
    SL.Text := C; SL.SaveToFile(P);
  finally SL.Free; end;
end;

procedure ConfigureAnythingLLM;
var P, C: String; SL: TStringList;
begin
  P := GetAppDataDir + '\\anythingllm-desktop\\storage\\plugins\\anythingllm_mcp_servers.json';
  if not FileExists(P) then begin
    ForceDirectories(ExtractFilePath(P));
    SL := TStringList.Create;
    try
      SL.Add('{');
      SL.Add('    "mcpServers": {');
      SL.Add('        "mcp-server-for-revit": {');
      SL.Add('            "command": "node",');
      SL.Add('            "args": ["' + ServerPathJson() + '"]');
      SL.Add('        }');
      SL.Add('    }');
      SL.Add('}');
      SL.SaveToFile(P);
    finally SL.Free; end;
    Log('Created AnythingLLM config');
  end else begin
    SL := TStringList.Create;
    try
      SL.LoadFromFile(P); C := SL.Text;
      if Pos(ServerKey, C) > 0 then begin
        ReplaceNpxServerEntry(C, False);
        SL.Text := C;
        SL.SaveToFile(P);
      Exit;
      end;
      StringChangeEx(C, '"mcpServers": {',
        '"mcpServers": {' + #13#10 + '        "mcp-server-for-revit": {' + #13#10 + '            "command": "node",' + #13#10 + '            "args": ["' + ServerPathJson() + '"]' + #13#10 + '        },', True);
      CleanTrailingCommas(C);
      SL.Text := C;
      SL.SaveToFile(P);
    finally SL.Free; end;
    Log('Updated AnythingLLM config');
  end;
end;

procedure RemoveFromAnythingLLM;
var P, C: String; SL: TStringList; S, E: Integer;
begin
  P := GetAppDataDir + '\\anythingllm-desktop\\storage\\plugins\\anythingllm_mcp_servers.json';
  if not FileExists(P) then Exit;
  SL := TStringList.Create;
  try
    SL.LoadFromFile(P); C := SL.Text;
    S := Pos('"mcp-server-for-revit"', C);
    if S = 0 then Exit;
    E := Pos('}', Copy(C, S, Length(C)));
    if E = 0 then Exit;
    E := S + E - 1;
    if (E + 1 <= Length(C)) and (C[E + 1] = ',') then Inc(E);
    Delete(C, S, E - S + 1);
    CleanTrailingCommas(C);
    SL.Text := C; SL.SaveToFile(P);
  finally SL.Free; end;
end;

procedure ConfigureOpencode;
var P, C: String; SL: TStringList;
begin
  P := GetUserProfilePath + '\\.config\\opencode\\opencode.json';
  if not FileExists(P) then begin
    ForceDirectories(ExtractFilePath(P));
    SL := TStringList.Create;
    try
      SL.Add('{');
      SL.Add('    "$schema": "https://opencode.ai/config.json",');
      SL.Add('    "mcp": {');
      SL.Add('        "mcp-server-for-revit": {');
      SL.Add('            "type": "local",');
      SL.Add('            "command": ["node", "' + ServerPathJson() + '"],');
      SL.Add('            "enabled": true');
      SL.Add('        }');
      SL.Add('    }');
      SL.Add('}');
      SL.SaveToFile(P);
    finally SL.Free; end;
    Log('Created opencode config');
  end else begin
    SL := TStringList.Create;
    try
      SL.LoadFromFile(P); C := SL.Text;
      if Pos(ServerKey, C) > 0 then begin
        ReplaceNpxServerEntry(C, True);
        SL.Text := C;
        SL.SaveToFile(P);
      Exit;
      end;
      StringChangeEx(C, '"mcp": {',
        '"mcp": {' + #13#10 + '        "mcp-server-for-revit": {' + #13#10 + '            "type": "local",' + #13#10 + '            "command": ["node", "' + ServerPathJson() + '"],' + #13#10 + '            "enabled": true' + #13#10 + '        },', True);
      CleanTrailingCommas(C);
      SL.Text := C;
      SL.SaveToFile(P);
    finally SL.Free; end;
    Log('Updated opencode config');
  end;
end;

procedure RemoveFromOpencode;
var P, C: String; SL: TStringList; S, E: Integer;
begin
  P := GetUserProfilePath + '\\.config\\opencode\\opencode.json';
  if not FileExists(P) then Exit;
  SL := TStringList.Create;
  try
    SL.LoadFromFile(P); C := SL.Text;
    S := Pos('"mcp-server-for-revit"', C);
    if S = 0 then Exit;
    E := Pos('}', Copy(C, S, Length(C)));
    if E = 0 then Exit;
    E := S + E - 1;
    if (E + 1 <= Length(C)) and (C[E + 1] = ',') then Inc(E);
    Delete(C, S, E - S + 1);
    CleanTrailingCommas(C);
    SL.Text := C; SL.SaveToFile(P);
  finally SL.Free; end;
end;

procedure CreateCommandSetPage;
var I: Integer;
  SetLabel: TNewStaticText;
  Names: array[0..2] of String;
begin
  SetPage := CreateCustomPage(wpSelectDir, 'Command Sets', 'Select which Command Sets to install:');

  SetLabel := TNewStaticText.Create(WizardForm);
  SetLabel.Parent := SetPage.Surface;
  SetLabel.SetBounds(ScaleX(20), ScaleY(10), ScaleX(400), ScaleY(20));
  SetLabel.Caption := 'All command sets are selected by default. Uncheck any you do not want:';
  SetLabel.Font.Style := [fsBold];

  Names[0] := 'DwgCommandSet';
  Names[1] := 'OffAxisCommandSet';
  Names[2] := 'RevitMCPCommandSet';

  for I := 0 to High(SetCBs) do begin
    SetCBs[I] := TNewCheckBox.Create(WizardForm);
    SetCBs[I].Parent := SetPage.Surface;
    SetCBs[I].SetBounds(ScaleX(20), ScaleY(40 + I * 30), ScaleX(600), ScaleY(20));
    SetCBs[I].Caption := Names[I];
    SetCBs[I].Checked := True;
  end;
end;

procedure CreateClientPage;
var Label1: TNewStaticText;
begin
  Page := CreateCustomPage(wpSelectDir, 'AI Client Configuration', 'Select which AI clients to configure for MCP server access:');

  Label1 := TNewStaticText.Create(WizardForm);
  Label1.Parent := Page.Surface;
  Label1.SetBounds(ScaleX(20), ScaleY(10), ScaleX(400), ScaleY(20));
  Label1.Caption := 'Detected clients are pre-checked:';
  Label1.Font.Style := [fsBold];

  ClaudeCB := TNewCheckBox.Create(WizardForm);
  ClaudeCB.Parent := Page.Surface;
  ClaudeCB.SetBounds(ScaleX(20), ScaleY(40), ScaleX(400), ScaleY(20));
  ClaudeCB.Caption := 'Claude Desktop (' + GetAppDataDir + '\\Claude\\)';
  ClaudeCB.Checked := FileExists(GetAppDataDir + '\\Claude\\claude_desktop_config.json');

  CursorCB := TNewCheckBox.Create(WizardForm);
  CursorCB.Parent := Page.Surface;
  CursorCB.SetBounds(ScaleX(20), ScaleY(65), ScaleX(400), ScaleY(20));
  CursorCB.Caption := 'Cursor (' + GetUserProfilePath + '\\.cursor\\)';
  CursorCB.Checked := DirExists(GetUserProfilePath + '\\.cursor');

  OpencodeCB := TNewCheckBox.Create(WizardForm);
  OpencodeCB.Parent := Page.Surface;
  OpencodeCB.SetBounds(ScaleX(20), ScaleY(90), ScaleX(400), ScaleY(20));
  OpencodeCB.Caption := 'opencode (' + GetUserProfilePath + '\\.config\\opencode\\)';
  OpencodeCB.Checked := DirExists(GetUserProfilePath + '\\.config\\opencode');

  AnythingLLMCB := TNewCheckBox.Create(WizardForm);
  AnythingLLMCB.Parent := Page.Surface;
  AnythingLLMCB.SetBounds(ScaleX(20), ScaleY(115), ScaleX(400), ScaleY(20));
  AnythingLLMCB.Caption := 'AnythingLLM (' + GetAppDataDir + '\\anythingllm-desktop\\)';
  AnythingLLMCB.Checked := DirExists(GetAppDataDir + '\\anythingllm-desktop');
end;

procedure InitializeWizard;
begin
  CreateCommandSetPage;
  CreateClientPage;
end;

function NextButtonClick(Page: Integer): Boolean;
var M: String;
begin
  Result := True;
  if Page = wpReady then begin
    if not IsNodeInstalled then begin
      M := 'Node.js is required but not found.' + #13#10 + #13#10
        + 'Install Node.js 20+ from https://nodejs.org/' + #13#10 + #13#10
        + 'The plugin will install but AI features won''t work.' + #13#10 + #13#10
        + 'Continue anyway?';
      if MsgBox(M, mbInformation, MB_YESNO) = IDNO then Result := False;
    end;
  end;
end;

procedure ConfigureDetectedClients;
begin
  if FileExists(GetAppDataDir + '\\Claude\\claude_desktop_config.json') or DirExists(GetAppDataDir + '\\Claude') then ConfigureClaudeDesktop;
  if DirExists(GetUserProfilePath + '\\.cursor') then ConfigureCursor;
  if DirExists(GetUserProfilePath + '\\.config\\opencode') then ConfigureOpencode;
  if DirExists(GetAppDataDir + '\\anythingllm-desktop') then ConfigureAnythingLLM;
end;

procedure CurStepChanged(CurStep: TSetupStep);
var AnyChecked: Boolean;
begin
  if CurStep = ssPostInstall then begin
    if IsRevitInstalled('2024') then CopyToRevitAddins('2024');
    if IsRevitInstalled('2025') then CopyToRevitAddins('2025');
    if IsRevitInstalled('2026') then CopyToRevitAddins('2026');
    AnyChecked := ClaudeCB.Checked or CursorCB.Checked or OpencodeCB.Checked or AnythingLLMCB.Checked;
    if not AnyChecked then ConfigureDetectedClients
    else begin
      if ClaudeCB.Checked then ConfigureClaudeDesktop;
      if CursorCB.Checked then ConfigureCursor;
      if OpencodeCB.Checked then ConfigureOpencode;
      if AnythingLLMCB.Checked then ConfigureAnythingLLM;
    end;
    MsgBox('Installation complete.' #13#10 #13#10 'Commands are disabled by default for your control. To expose model commands to AI clients:' #13#10 '1. In Revit, open the plugin Settings page' #13#10 '2. Enable the commands you want, then click Save' #13#10 '3. Click the Revit MCP Switch to start the server', mbInformation, MB_OK);
  end;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var I: Integer;
begin
  if CurUninstallStep = usUninstall then begin
    for I := 2020 to 2026 do RemoveFromRevitAddins(IntToStr(I));
    RemoveFromClaudeDesktop;
    RemoveFromCursor;
    RemoveFromOpencode;
    RemoveFromAnythingLLM;
  end;
end;