; MCP Servers for Revit Installer - Generated by build-installer.ps1

[Setup]
AppName=MCP Servers for Revit
AppVersion=1.0.0
AppPublisher=MCP Servers for Revit
AppPublisherURL=https://github.com/mcp-servers-for-revit/mcp-servers-for-revit
DefaultDirName={autopf}\MCP Servers for Revit
DefaultGroupName=MCP Servers for Revit
OutputDir=C:\dev\mcp-servers-for-revit\installer\output
OutputBaseFilename=mcp-servers-for-revit-setup
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "staged\2024\*"; DestDir: "{app}\RevitPlugins\2024"; Flags: recursesubdirs ignoreversion

[Icons]
Name: "{group}\Uninstall MCP Servers for Revit"; Filename: "{uninstallexe}"

[Code]
const
  RevitRegKey = 'SOFTWARE\\Autodesk\\Revit\\Autodesk Revit ';
  ServerKey = 'mcp-server-for-revit';
  CommandSetFolder = 'revit_mcp_plugin\\Commands';

var
  Page: TWizardPage;
  SetPage: TWizardPage;
  ClaudeCB, CursorCB, OpencodeCB: TNewCheckBox;

var SetCBs: array[0..1] of TNewCheckBox;

function GetAppDataDir: String;
begin
  Result := GetEnv('APPDATA');
end;

function GetUserProfilePath: String;
begin
  Result := GetEnv('USERPROFILE');
end;

function IsNodeInstalled: Boolean;
var RC: Integer;
begin
  Result := Exec('cmd', '/c node --version >nul 2>&1', '', SW_HIDE, ewWaitUntilTerminated, RC) and (RC = 0);
end;

function IsRevitInstalled(Y: String): Boolean;
begin
  Result := RegKeyExists(HKLM, RevitRegKey + Y) or RegKeyExists(HKCU, RevitRegKey + Y);
end;

procedure PruneCommandSets(Src: String);
var CmdDir: String; I: Integer;
begin
  CmdDir := Src + '\\revit_mcp_plugin\\Commands';
  if not DirExists(CmdDir) then Exit;
  for I := 0 to High(SetCBs) do begin
    if not SetCBs[I].Checked then begin
      DelTree(CmdDir + '\\' + SetCBs[I].Caption, True, True, True);
      Log('Removed unselected command set: ' + SetCBs[I].Caption);
    end;
  end;
end;

procedure CopyToRevitAddins(Year: String);
var Src, Dst: String; BAT: TStringList; RC: Integer;
begin
  Src := ExpandConstant('{app}\\RevitPlugins\\' + Year);
  Dst := GetAppDataDir + '\\Autodesk\\Revit\\Addins\\' + Year;
  if not DirExists(Src) then begin Log('Missing: ' + Src); Exit; end;
  PruneCommandSets(Src);
  ForceDirectories(Dst);
  BAT := TStringList.Create;
  try
    BAT.Add('@echo off');
    BAT.Add('xcopy "' + Src + '\\*" "' + Dst + '\\" /E /I /Y /Q');
    BAT.SaveToFile(ExpandConstant('{tmp}\\copy_' + Year + '.bat'));
  finally BAT.Free; end;
  Exec('cmd', '/c "' + ExpandConstant('{tmp}\\copy_' + Year + '.bat') + '"', '', SW_HIDE, ewWaitUntilTerminated, RC);
  Log('Copied plugin to ' + Dst);
end;

procedure RemoveFromRevitAddins(Year: String);
var D: String;
begin
  D := GetAppDataDir + '\\Autodesk\\Revit\\Addins\\' + Year;
  if FileExists(D + '\\mcp-servers-for-revit.addin') then DeleteFile(D + '\\mcp-servers-for-revit.addin');
  if DirExists(D + '\\revit_mcp_plugin') then DelTree(D + '\\revit_mcp_plugin', True, True, True);
end;

procedure CleanTrailingCommas(var C: String);
var I, J: Integer;
begin
  for I := 1 to Length(C) do begin
    if C[I] = ',' then begin
      J := I + 1;
      while (J <= Length(C)) and ((C[J] = ' ') or (C[J] = #9) or (C[J] = #13) or (C[J] = #10)) do Inc(J);
      if (J <= Length(C)) and ((C[J] = '}') or (C[J] = ']')) then C[I] := ' ';
    end;
  end;
end;

procedure ConfigureClaudeDesktop;
var P, C: String; SL: TStringList;
begin
  P := GetAppDataDir + '\\Claude\\claude_desktop_config.json';
  if not FileExists(P) then begin
    ForceDirectories(ExtractFilePath(P));
    SL := TStringList.Create;
    try
      SL.Add('{');
      SL.Add('    "mcpServers": {');
      SL.Add('        "mcp-server-for-revit": {');
      SL.Add('            "command": "cmd",');
      SL.Add('            "args": ["/c", "npx", "-y", "mcp-server-for-revit"]');
      SL.Add('        }');
      SL.Add('    }');
      SL.Add('}');
      SL.SaveToFile(P);
    finally SL.Free; end;
    Log('Created Claude Desktop config');
  end else begin
    SL := TStringList.Create;
    try
      SL.LoadFromFile(P); C := SL.Text;
      if Pos(ServerKey, C) > 0 then begin Log('Claude Desktop already configured'); Exit; end;
      StringChangeEx(C, '"mcpServers": {',
        '"mcpServers": {' + #13#10 + '        "mcp-server-for-revit": {' + #13#10 + '            "command": "cmd",' + #13#10 + '            "args": ["/c", "npx", "-y", "mcp-server-for-revit"]' + #13#10 + '        },', True);
      CleanTrailingCommas(C);
      SL.Text := C;
      SL.SaveToFile(P);
    finally SL.Free; end;
    Log('Updated Claude Desktop config');
  end;
end;

procedure RemoveFromClaudeDesktop;
var P, C: String; SL: TStringList; S, E: Integer;
begin
  P := GetAppDataDir + '\\Claude\\claude_desktop_config.json';
  if not FileExists(P) then Exit;
  SL := TStringList.Create;
  try
    SL.LoadFromFile(P); C := SL.Text;
    S := Pos('"mcp-server-for-revit"', C);
    if S = 0 then Exit;
    E := Pos('}', Copy(C, S, Length(C)));
    if E = 0 then Exit;
    E := S + E - 1;
    if (E + 1 <= Length(C)) and (C[E + 1] = ',') then Inc(E);
    Delete(C, S, E - S + 1);
    CleanTrailingCommas(C);
    SL.Text := C; SL.SaveToFile(P);
  finally SL.Free; end;
end;

procedure ConfigureCursor;
var P, C: String; SL: TStringList;
begin
  P := GetUserProfilePath + '\\.cursor\\mcp.json';
  if not FileExists(P) then begin
    ForceDirectories(ExtractFilePath(P));
    SL := TStringList.Create;
    try
      SL.Add('{');
      SL.Add('    "mcpServers": {');
      SL.Add('        "mcp-server-for-revit": {');
      SL.Add('            "command": "npx",');
      SL.Add('            "args": ["-y", "mcp-server-for-revit"]');
      SL.Add('        }');
      SL.Add('    }');
      SL.Add('}');
      SL.SaveToFile(P);
    finally SL.Free; end;
    Log('Created Cursor config');
  end else begin
    SL := TStringList.Create;
    try
      SL.LoadFromFile(P); C := SL.Text;
      if Pos(ServerKey, C) > 0 then begin Log('Cursor already configured'); Exit; end;
      StringChangeEx(C, '"mcpServers": {',
        '"mcpServers": {' + #13#10 + '        "mcp-server-for-revit": {' + #13#10 + '            "command": "npx",' + #13#10 + '            "args": ["-y", "mcp-server-for-revit"]' + #13#10 + '        },', True);
      CleanTrailingCommas(C);
      SL.Text := C;
      SL.SaveToFile(P);
    finally SL.Free; end;
    Log('Updated Cursor config');
  end;
end;

procedure RemoveFromCursor;
var P, C: String; SL: TStringList; S, E: Integer;
begin
  P := GetUserProfilePath + '\\.cursor\\mcp.json';
  if not FileExists(P) then Exit;
  SL := TStringList.Create;
  try
    SL.LoadFromFile(P); C := SL.Text;
    S := Pos('"mcp-server-for-revit"', C);
    if S = 0 then Exit;
    E := Pos('}', Copy(C, S, Length(C)));
    if E = 0 then Exit;
    E := S + E - 1;
    if (E + 1 <= Length(C)) and (C[E + 1] = ',') then Inc(E);
    Delete(C, S, E - S + 1);
    CleanTrailingCommas(C);
    SL.Text := C; SL.SaveToFile(P);
  finally SL.Free; end;
end;

procedure ConfigureOpencode;
var P, C: String; SL: TStringList;
begin
  P := GetUserProfilePath + '\\.config\\opencode\\opencode.json';
  if not FileExists(P) then begin
    ForceDirectories(ExtractFilePath(P));
    SL := TStringList.Create;
    try
      SL.Add('{');
      SL.Add('    "$schema": "https://opencode.ai/config.json",');
      SL.Add('    "mcp": {');
      SL.Add('        "mcp-server-for-revit": {');
      SL.Add('            "type": "local",');
      SL.Add('            "command": ["npx", "-y", "mcp-server-for-revit"],');
      SL.Add('            "enabled": true');
      SL.Add('        }');
      SL.Add('    }');
      SL.Add('}');
      SL.SaveToFile(P);
    finally SL.Free; end;
    Log('Created opencode config');
  end else begin
    SL := TStringList.Create;
    try
      SL.LoadFromFile(P); C := SL.Text;
      if Pos(ServerKey, C) > 0 then begin Log('opencode already configured'); Exit; end;
      StringChangeEx(C, '"mcp": {',
        '"mcp": {' + #13#10 + '        "mcp-server-for-revit": {' + #13#10 + '            "type": "local",' + #13#10 + '            "command": ["npx", "-y", "mcp-server-for-revit"],' + #13#10 + '            "enabled": true' + #13#10 + '        },', True);
      CleanTrailingCommas(C);
      SL.Text := C;
      SL.SaveToFile(P);
    finally SL.Free; end;
    Log('Updated opencode config');
  end;
end;

procedure RemoveFromOpencode;
var P, C: String; SL: TStringList; S, E: Integer;
begin
  P := GetUserProfilePath + '\\.config\\opencode\\opencode.json';
  if not FileExists(P) then Exit;
  SL := TStringList.Create;
  try
    SL.LoadFromFile(P); C := SL.Text;
    S := Pos('"mcp-server-for-revit"', C);
    if S = 0 then Exit;
    E := Pos('}', Copy(C, S, Length(C)));
    if E = 0 then Exit;
    E := S + E - 1;
    if (E + 1 <= Length(C)) and (C[E + 1] = ',') then Inc(E);
    Delete(C, S, E - S + 1);
    CleanTrailingCommas(C);
    SL.Text := C; SL.SaveToFile(P);
  finally SL.Free; end;
end;

procedure CreateCommandSetPage;
var I: Integer;
  SetLabel: TNewStaticText;
begin
  SetPage := CreateCustomPage(wpSelectDir, 'Command Sets', 'Select which Command Sets to install:');

  SetLabel := TNewStaticText.Create(WizardForm);
  SetLabel.Parent := SetPage.Surface;
  SetLabel.SetBounds(ScaleX(20), ScaleY(10), ScaleX(400), ScaleY(20));
  SetLabel.Caption := 'All command sets are selected by default. Uncheck any you do not want:';
  SetLabel.Font.Style := [fsBold];

  for I := 0 to High(SetCBs) do begin
    SetCBs[I] := TNewCheckBox.Create(WizardForm);
    SetCBs[I].Parent := SetPage.Surface;
    SetCBs[I].SetBounds(ScaleX(20), ScaleY(40 + I * 30), ScaleX(600), ScaleY(20));
    SetCBs[0].Caption := 'OffAxisCommandSet';
    SetCBs[0].Checked := True;
    SetCBs[1].Caption := 'RevitMCPCommandSet';
    SetCBs[1].Checked := True;
  end;
end;

procedure CreateClientPage;
var Label1: TNewStaticText;
begin
  Page := CreateCustomPage(wpSelectDir, 'AI Client Configuration', 'Select which AI clients to configure for MCP server access:');

  Label1 := TNewStaticText.Create(WizardForm);
  Label1.Parent := Page.Surface;
  Label1.SetBounds(ScaleX(20), ScaleY(10), ScaleX(400), ScaleY(20));
  Label1.Caption := 'Detected clients are pre-checked:';
  Label1.Font.Style := [fsBold];

  ClaudeCB := TNewCheckBox.Create(WizardForm);
  ClaudeCB.Parent := Page.Surface;
  ClaudeCB.SetBounds(ScaleX(20), ScaleY(40), ScaleX(400), ScaleY(20));
  ClaudeCB.Caption := 'Claude Desktop (' + GetAppDataDir + '\\Claude\\)';
  ClaudeCB.Checked := FileExists(GetAppDataDir + '\\Claude\\claude_desktop_config.json');

  CursorCB := TNewCheckBox.Create(WizardForm);
  CursorCB.Parent := Page.Surface;
  CursorCB.SetBounds(ScaleX(20), ScaleY(65), ScaleX(400), ScaleY(20));
  CursorCB.Caption := 'Cursor (' + GetUserProfilePath + '\\.cursor\\)';
  CursorCB.Checked := DirExists(GetUserProfilePath + '\\.cursor');

  OpencodeCB := TNewCheckBox.Create(WizardForm);
  OpencodeCB.Parent := Page.Surface;
  OpencodeCB.SetBounds(ScaleX(20), ScaleY(90), ScaleX(400), ScaleY(20));
  OpencodeCB.Caption := 'opencode (' + GetUserProfilePath + '\\.config\\opencode\\)';
  OpencodeCB.Checked := DirExists(GetUserProfilePath + '\\.config\\opencode');
end;

procedure InitializeWizard;
begin
  CreateCommandSetPage;
  CreateClientPage;
end;

function NextButtonClick(Page: Integer): Boolean;
var M: String;
begin
  Result := True;
  if Page = wpReady then begin
    if not IsNodeInstalled then begin
      M := 'Node.js is required but not found.' + #13#10 + #13#10
        + 'Install Node.js 18+ from https://nodejs.org/' + #13#10 + #13#10
        + 'The plugin will install but AI features won''t work.' + #13#10 + #13#10
        + 'Continue anyway?';
      if MsgBox(M, mbInformation, MB_YESNO) = IDNO then Result := False;
    end;
  end;
end;

procedure ConfigureDetectedClients;
begin
  if FileExists(GetAppDataDir + '\\Claude\\claude_desktop_config.json') or DirExists(GetAppDataDir + '\\Claude') then ConfigureClaudeDesktop;
  if DirExists(GetUserProfilePath + '\\.cursor') then ConfigureCursor;
  if DirExists(GetUserProfilePath + '\\.config\\opencode') then ConfigureOpencode;
end;

procedure CurStepChanged(CurStep: TSetupStep);
var AnyChecked: Boolean;
begin
  if CurStep = ssPostInstall then begin
    if IsRevitInstalled('2024') then CopyToRevitAddins('2024');
    AnyChecked := ClaudeCB.Checked or CursorCB.Checked or OpencodeCB.Checked;
    if not AnyChecked then ConfigureDetectedClients
    else begin
      if ClaudeCB.Checked then ConfigureClaudeDesktop;
      if CursorCB.Checked then ConfigureCursor;
      if OpencodeCB.Checked then ConfigureOpencode;
    end;
  end;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var I: Integer;
begin
  if CurUninstallStep = usUninstall then begin
    for I := 2020 to 2026 do RemoveFromRevitAddins(IntToStr(I));
    RemoveFromClaudeDesktop;
    RemoveFromCursor;
    RemoveFromOpencode;
  end;
end;